"""Add advanced features for ultra-fast sending

Revision ID: 002_add_advanced_features
Revises: 001_initial_migration
Create Date: 2024-01-01 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '002_add_advanced_features'
down_revision = '001_initial_migration'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add new columns to accounts table
    op.add_column('accounts', sa.Column('user_count', sa.Integer(), nullable=True, default=0))
    op.add_column('accounts', sa.Column('daily_quota', sa.Integer(), nullable=True, default=2000))
    op.add_column('accounts', sa.Column('hourly_quota', sa.Integer(), nullable=True, default=250))
    op.add_column('accounts', sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True))
    
    # Create users table
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'RATE_LIMITED', 'ERROR', name='userstatus'), nullable=True),
    sa.Column('daily_sent_count', sa.Integer(), nullable=True, default=0),
    sa.Column('hourly_sent_count', sa.Integer(), nullable=True, default=0),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    
    # Add new columns to campaigns table
    op.add_column('campaigns', sa.Column('custom_headers', sa.JSON(), nullable=True))
    op.add_column('campaigns', sa.Column('test_email', sa.String(), nullable=True))
    op.add_column('campaigns', sa.Column('selected_accounts', sa.JSON(), nullable=True))
    op.add_column('campaigns', sa.Column('send_rate_per_minute', sa.Integer(), nullable=True, default=1000))
    op.add_column('campaigns', sa.Column('preparation_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('campaigns', sa.Column('preparation_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('campaigns', sa.Column('sending_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('campaigns', sa.Column('sending_completed_at', sa.DateTime(timezone=True), nullable=True))
    
    # Update campaign status enum to include new values
    op.execute("ALTER TYPE campaignstatus ADD VALUE 'PREPARING'")
    op.execute("ALTER TYPE campaignstatus ADD VALUE 'READY'")
    
    # Update recipient status enum to include new values  
    op.execute("ALTER TYPE recipientstatus ADD VALUE 'ASSIGNED'")
    op.execute("ALTER TYPE recipientstatus ADD VALUE 'SENDING'")
    
    # Add new columns to recipients table
    op.add_column('recipients', sa.Column('custom_data', sa.JSON(), nullable=True))
    op.add_column('recipients', sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_recipients_email'), 'recipients', ['email'], unique=False)
    
    # Remove account_id foreign key from campaigns table (no longer needed)
    op.drop_constraint('campaigns_account_id_fkey', 'campaigns', type_='foreignkey')
    op.drop_column('campaigns', 'account_id')
    
    # Create recipient_assignments table
    op.create_table('recipient_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True, default=0),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipient_assignments_id'), 'recipient_assignments', ['id'], unique=False)
    
    # Create sending_batches table
    op.create_table('sending_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipient_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True, default='pending'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('send_rate', sa.Float(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sending_batches_id'), 'sending_batches', ['id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sending_batches_id'), table_name='sending_batches')
    op.drop_table('sending_batches')
    op.drop_index(op.f('ix_recipient_assignments_id'), table_name='recipient_assignments')
    op.drop_table('recipient_assignments')
    op.drop_index(op.f('ix_recipients_email'), table_name='recipients')
    op.drop_column('recipients', 'assigned_at')
    op.drop_column('recipients', 'custom_data')
    op.drop_column('campaigns', 'sending_completed_at')
    op.drop_column('campaigns', 'sending_started_at')
    op.drop_column('campaigns', 'preparation_completed_at')
    op.drop_column('campaigns', 'preparation_started_at')
    op.drop_column('campaigns', 'send_rate_per_minute')
    op.drop_column('campaigns', 'selected_accounts')
    op.drop_column('campaigns', 'test_email')
    op.drop_column('campaigns', 'custom_headers')
    op.add_column('campaigns', sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('campaigns_account_id_fkey', 'campaigns', 'accounts', ['account_id'], ['id'])
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_column('accounts', 'last_sync_at')
    op.drop_column('accounts', 'hourly_quota')
    op.drop_column('accounts', 'daily_quota')
    op.drop_column('accounts', 'user_count')
    # ### end Alembic commands ###